version: '3.7'

networks:
  swarm-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.0.1.0/24
          gateway: 192.0.1.1
    name: swarm-net

services:
  helix.swarm:
    image: perforce/helix-swarm:latest
    hostname: 'helix_swarm'
    container_name: 'helix.swarm'
    restart: unless-stopped
    volumes:
      - ~/.swarm/swarm-data:/opt/perforce/swarm/data
      - ~/.swarm/www:/var/www
    ports:
      - 1667:1667
    working_dir: /opt/perforce/swarm
    depends_on:
      - helix.redis
    tty: false
    env_file:
      - ~/.swarm/.env
    networks:
      - swarm-net

  helix.redis:
    image: redis:latest
    hostname: 'helix_redis'
    container_name: 'helix.redis'
    restart: unless-stopped
    command: redis-server --protected-mode no --port 7379 --appendonly yes
    volumes:
      - ~/.swarm/redis-data:/data
    networks:
      - swarm-net
