version: '3.7'

networks:
  teamcity_network:
    name: teamcity_network
    driver: bridge
    ipam:
      config:
        - subnet: '172.19.0.0/16'
          gateway: '172.19.0.1'

services:
  teamcity.db:
    image: postgres:latest
    hostname: 'teamcity_db'
    container_name: 'teamcity.db'
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    env_file:
      - ~/.teamcity/postgres.env
    ports:
      - '5432:5432'
    volumes:
      - ~/.teamicty/db:/var/lib/postgresql/data
    networks:
      teamcity_network:
        ipv4_address: 172.19.0.2

  teamcity.server:
    image: jetbrains/teamcity-server:latest
    container_name: 'teamcity.server'
    hostname: 'teamcity_server'
    restart: unless-stopped
    ports:
      - '8111:8111'
    volumes:
      - ~/.teamcity/data:/data/teamcity_server/datadir
      - ~/.teamcity/logs:/opt/teamcity/logs
    depends_on:
      - teamcity.db
    networks:
      teamcity_network:
        ipv4_address: 172.19.0.3

  teamcity.agent.rocket:
    image: jetbrains/teamcity-agent:latest
    container_name: 'teamcity.agent.rocket'
    hostname: 'teamcity_agent_rocket'
    restart: unless-stopped
    privileged: true
    depends_on:
      - teamcity.server
    volumes:
      - ~/.teamcity/agent_rocket:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=http://172.19.0.3:8111
      - OWN_ADDRESS=172.19.0.4
      - OWN_PORT=9090
      - AGENT_NAME=rocket
    networks:
      teamcity_network:
        ipv4_address: 172.19.0.4
  
  teamcity.agent.plasma:
    image: jetbrains/teamcity-agent:latest
    container_name: 'teamcity.agent.plasma'
    hostname: 'teamcity_agent_plasma'
    restart: unless-stopped
    privileged: true
    depends_on:
      - teamcity.server
    volumes:
      - ~/.teamcity/agent_plasma:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=http://172.19.0.3:8111
      - OWN_ADDRESS=172.19.0.5
      - OWN_PORT=9091
      - AGENT_NAME=plasma
    networks:
      teamcity_network:
        ipv4_address: 172.19.0.5
  
  teamcity.agent.idro:
    image: jetbrains/teamcity-agent:latest
    container_name: 'teamcity.agent.idro'
    hostname: 'teamcity_agent_idro'
    restart: unless-stopped
    privileged: true
    depends_on:
      - teamcity.server
    volumes:
      - ~/.teamcity/agent_idro:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=http://172.19.0.3:8111
      - OWN_ADDRESS=172.19.0.6
      - OWN_PORT=9092
      - AGENT_NAME=idro
    networks:
      teamcity_network:
        ipv4_address: 172.19.0.6
  
  teamcity.agent.magma:
    image: jetbrains/teamcity-agent:latest
    container_name: 'teamcity.agent.magma'
    hostname: 'teamcity_agent_magma'
    restart: unless-stopped
    privileged: true
    depends_on:
      - teamcity.server
    volumes:
      - ~/.teamcity/agent_magma:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=http://172.19.0.3:8111
      - OWN_ADDRESS=172.19.0.7
      - OWN_PORT=9093
      - AGENT_NAME=magma
    networks:
      teamcity_network:
        ipv4_address: 172.19.0.7
